// Code generated by Kitex v0.8.0. DO NOT EDIT.

package workerservice

import (
	"context"
	client "github.com/cloudwego/kitex/client"
	callopt "github.com/cloudwego/kitex/client/callopt"
	v1 "github.com/user823/Sophie/api/thrift/schedule/v1"
)

// Client is designed to provide IDL-compatible methods with call-option parameter for kitex framework.
type Client interface {
	CreateJob(ctx context.Context, job *v1.JobInfo, callOptions ...callopt.Option) (r *v1.BaseResp, err error)
	RemoveJobs(ctx context.Context, jobIds []int64, callOptions ...callopt.Option) (r *v1.BaseResp, err error)
	PauseJobs(ctx context.Context, jobIds []int64, callOptions ...callopt.Option) (r *v1.BaseResp, err error)
	ResumeJobs(ctx context.Context, jobIds []int64, callOptions ...callopt.Option) (r *v1.BaseResp, err error)
	Run(ctx context.Context, jobIds []int64, callOptions ...callopt.Option) (r *v1.BaseResp, err error)
	UpdateJob(ctx context.Context, job *v1.JobInfo, callOptions ...callopt.Option) (r *v1.BaseResp, err error)
}

// NewClient creates a client for the service defined in IDL.
func NewClient(destService string, opts ...client.Option) (Client, error) {
	var options []client.Option
	options = append(options, client.WithDestService(destService))

	options = append(options, opts...)

	kc, err := client.NewClient(serviceInfo(), options...)
	if err != nil {
		return nil, err
	}
	return &kWorkerServiceClient{
		kClient: newServiceClient(kc),
	}, nil
}

// MustNewClient creates a client for the service defined in IDL. It panics if any error occurs.
func MustNewClient(destService string, opts ...client.Option) Client {
	kc, err := NewClient(destService, opts...)
	if err != nil {
		panic(err)
	}
	return kc
}

type kWorkerServiceClient struct {
	*kClient
}

func (p *kWorkerServiceClient) CreateJob(ctx context.Context, job *v1.JobInfo, callOptions ...callopt.Option) (r *v1.BaseResp, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.CreateJob(ctx, job)
}

func (p *kWorkerServiceClient) RemoveJobs(ctx context.Context, jobIds []int64, callOptions ...callopt.Option) (r *v1.BaseResp, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.RemoveJobs(ctx, jobIds)
}

func (p *kWorkerServiceClient) PauseJobs(ctx context.Context, jobIds []int64, callOptions ...callopt.Option) (r *v1.BaseResp, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.PauseJobs(ctx, jobIds)
}

func (p *kWorkerServiceClient) ResumeJobs(ctx context.Context, jobIds []int64, callOptions ...callopt.Option) (r *v1.BaseResp, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.ResumeJobs(ctx, jobIds)
}

func (p *kWorkerServiceClient) Run(ctx context.Context, jobIds []int64, callOptions ...callopt.Option) (r *v1.BaseResp, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.Run(ctx, jobIds)
}

func (p *kWorkerServiceClient) UpdateJob(ctx context.Context, job *v1.JobInfo, callOptions ...callopt.Option) (r *v1.BaseResp, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.UpdateJob(ctx, job)
}
