# 使用minio 对象存储服务，也可以更换成华为云、七牛云等
driver: minio

minio:
  endpoint: ${MINIO_HOST}
  bucket: sophie
  access_key: ${MINIO_ACCESSKEY}
  secret_key: ${MINIO_ACCESSSECRET}
  use_ssl: false

log:
  output_paths: ${LOG_OUTPUT_PATH}
  error_output_paths: ${LOG_ERR_OUTPUT_PATH}
  level: ${LOG_LEVEL}
  disable_caller: false
  disable_stacktrace: false
  # 开发者模式
  development: false
  # 禁用log
  disable_logger: false
  name: sophie-gateway-logger
  #  skip_caller: 3
  # 是否开启日志聚合
  aggregation: ${LOG_AGGREGATION}

# 可观测性配置
availability:
  trace_enable: true
  # jaeger
  trace_endpoint: ${JAEGER_HOST}
  # 需要配置promethus
  metric_enable: false
  profiling: false

# rpc_server配置
rpc_server:
  bind_address: ${SOPHIE_FILE_ADDRESS}
  bind_port: ${SOPHIE_FILE_PORT}
  # 多路复用
  enable_mux_connection: true
  max_conn_idle_time: 30m
  # 限流
  qps_limit: ${SOPHIE_FILE_QPS}
  # 连接数限制
  connection_limit: ${SOPHIE_FILE_CONN_LIMIT}
  # 关停时间
  # exit_wait_time: 8s

# 服务注册
service_register:
  addrs: ${ETCD_HOST}
  username: ${ETCD_USERNAME}
  password: ${ETCD_PASSWORD}
  max_attemt_times: 5
#  observer_delay: 10s
#  retry_delay: 5s
#  TTL: 60

# redis 配置
redis:
  addrs: ${REDIS_HOST}
  username: ${REDIS_USERNAME}
  password: ${REDIS_PASSWORD}
#  database: 0
#  master_name:
#  optimisation_max_idle: 2000
#  optimisation_max_active: 4000

# 日志聚合
aggregation:
  # 日志聚合工作线程数
  pool_size: 50
  # 日志聚合缓冲区大小
  records_buffer_size: 1000
  # 刷新间隔（毫秒）
  flush_interval: 200
  # 日志转存时间
  storage_expiration_time: 24h
  producer: "redis"

  # 配置rocketmq 转存
  # producer: "rocketmq"
  #   endpoints: ${ROCKETMQ_HOST}
  #   access_key: ${ROCKETMQ_ACCESSKEY}
  #   access_secret: ${ROCKETMQ_ACCESSSECET}
#  timeout: 0
#  enable_cluster: false
#  use_ssl: false
#  ssl_insecure_skip_verify: false
