// Code generated by Kitex v0.8.0. DO NOT EDIT.
package systemservice

import (
	server "github.com/cloudwego/kitex/server"
	v1 "github.com/user823/Sophie/api/thrift/system/v1"
)

// NewServer creates a server.Server with the given handler and options.
func NewServer(handler v1.SystemService, opts ...server.Option) server.Server {
	var options []server.Option

	options = append(options, opts...)

	svr := server.NewServer(options...)
	if err := svr.RegisterService(serviceInfo(), handler); err != nil {
		panic(err)
	}
	return svr
}
