driver: minio

minio:
  endpoint: 10.211.55.3:9000
  bucket: sophie
  access_key: sophie
  secret_key: 12345678
  use_ssl: false

log:
  aggregation: false
  name: sophie-file-logger

rpc_server:
  bind_address: 127.0.0.1
  bind_port: 8083