log:
  aggregation: false
  name: sophie-system-logger

rpc_server:
  bind_address: 127.0.0.1
  bind_port: 8082

availability:
  trace_enable: true
  trace_endpoint: 127.0.0.1:4317
  metric_enable: false
