generic:
  healthz: true
#  middlewares: accesslog

availability:
  trace_enable: true
  trace_endpoint: 127.0.0.1:4317
  metric_enable: false

insecure:
  bind_port: 8080

secure:
  bind_port: 9090
  tls:
    cert_file: /home/amber/.cert/sophie-gateway.pem
    private_key_file: /home/amber/.cert/sophie-gateway-key.pem

jwt:
  timeout: 1h

log:
  aggregation: false
  name: sophie-gateway-logger

