generic:
  healthz: true

insecure:
  bind_port: 8086

log:
  level: INFO

# consumer 端配置
# 订阅redis
sub_redis:
  addrs: 127.0.0.1:6379
  username: sophie
  password: 123456
  database: 0
  optimisation_max_idle: 1000
  optimisation_max_active: 4000
  timeout: 0
  enable_cluster: false
  use_ssl: false

# 订阅rocketmq
sub_rocketmq:
  rmq_endpoints: 127.0.0.1:8081
  access_key: sophie
  access_secret: 123456

# 指定输出端
exporters: elasticsearch_exporter
filters:
  log_level: 0
timeout: 3s

# exporter 端配置
pub_elasticsearch:
  target_indices: sophie_record_aggregation
  elasticsearch:
    addrs: https://127.0.0.1:9200
    username: sophie
    password: 123456
    max_idle: 10
    max_retry_times: 3
    use_ssl: false
    timeout: 3s
